blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions / General Questions
    url: https://github.com/pbasualdo/qruns-releases/discussions
    about: Please use discussions for general questions or community support.
